PHOENIX-5572 httpclient NoClassDefFoundError due to old httpcore version
exclude httpcore from the tephra dependency, so that we get httpcore via hadoop3->httpclient

Closes #634